server:
    port: 0
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8081/auth/realms/demoRealm
    application:
        name: microservice2
eureka:
    client:
        service-url:
                defaultZone: http://localhost:8010/eureka
    instance:
        instance-id: ${spring.application.name}:${instanceId:${random.value}}