server:
    port: 8080
spring:
    cloud:
        gateway:
            routes:
            -   filters:
                - RemoveRequestHeader=Cookie
                id: users-status-check
                predicates:
                - Path=/users/status/check
                - Method=GET
                uri: lb://ouathDemo
            -   filters:
                - RemoveRequestHeader=Cookie
                id: microservice2
                predicates:
                - Path=/microservice2
                - Method=GET
                uri: lb://microservice2
    application:
        name: api-gateway
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8010/eureka
    instance:
        instance-id: ${spring.application.name}:${instanceId:${random.value}}
