server:
  port: 8083
spring:
  cloud:
    gateway:
      routes:
        -id : users-status-check
        uri: http://localhost:8082
        predicates:
          - Path=/users/status/check
          - Method=GET
        filters:
          - RemoveRequestHeader=Cookie